import PDFDocument from 'pdfkit';

export type SectionPayload = {
  title: string;
  summary?: string;
  metrics?: { label: string; value: string }[];
  table?: { columns: string[]; rows: string[][] };
  bullets?: string[];
  empty?: string;
};

export type ReportDoc = {
  title: string;
  projectName: string;
  domain: string | null;
  period: string;
  generatedAt: Date;
  sections: SectionPayload[];
};

const esc = (s: string) => s.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);

/** Self-contained, printable HTML report (no external assets or scripts). */
export function renderHtml(doc: ReportDoc) {
  const section = (s: SectionPayload) => `
  <section>
    <h2>${esc(s.title)}</h2>
    ${s.summary ? `<p class="summary">${esc(s.summary)}</p>` : ''}
    ${s.metrics?.length ? `<div class="metrics">${s.metrics.map((m) => `<div><b>${esc(m.value)}</b><span>${esc(m.label)}</span></div>`).join('')}</div>` : ''}
    ${s.bullets?.length ? `<ul>${s.bullets.map((b) => `<li>${esc(b)}</li>`).join('')}</ul>` : ''}
    ${
      s.table?.rows.length
        ? `<table><thead><tr>${s.table.columns.map((c) => `<th>${esc(c)}</th>`).join('')}</tr></thead><tbody>${s.table.rows
            .map((r) => `<tr>${r.map((c) => `<td>${esc(c)}</td>`).join('')}</tr>`)
            .join('')}</tbody></table>`
        : ''
    }
    ${s.empty && !s.table?.rows.length && !s.bullets?.length && !s.metrics?.length ? `<p class="empty">${esc(s.empty)}</p>` : ''}
  </section>`;
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(doc.title)}</title>
<style>
  body{font-family:Inter,Segoe UI,Arial,sans-serif;color:#0f172a;margin:0;background:#f6f8fb}
  main{max-width:960px;margin:0 auto;padding:40px 24px}
  header{border-bottom:3px solid #16B364;padding-bottom:16px;margin-bottom:24px}
  header small{color:#0B3D2E;font-weight:700;letter-spacing:.12em}
  h1{margin:6px 0 4px;font-size:28px} .meta{color:#475569;font-size:14px}
  section{background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:20px;margin-bottom:18px;break-inside:avoid}
  h2{margin:0 0 10px;font-size:18px;color:#0B3D2E} .summary{color:#334155}
  .metrics{display:flex;flex-wrap:wrap;gap:12px;margin:12px 0}.metrics div{flex:1 1 140px;border:1px solid #e2e8f0;border-radius:10px;padding:12px}
  .metrics b{display:block;font-size:22px}.metrics span{color:#64748b;font-size:13px}
  table{width:100%;border-collapse:collapse;font-size:13px;margin-top:8px}th,td{text-align:left;padding:8px;border-bottom:1px solid #e2e8f0;vertical-align:top}th{background:#f1f5f9}
  .empty{color:#64748b;font-style:italic} footer{color:#94a3b8;font-size:12px;text-align:center;margin-top:24px}
  @media print{body{background:#fff}section{border-color:#cbd5e1}}
</style></head>
<body><main>
<header><small>AMPLIVERIFY · AUDIT • OPTIMIZE • VERIFY</small><h1>${esc(doc.title)}</h1>
<div class="meta">${esc(doc.projectName)}${doc.domain ? ` · ${esc(doc.domain)}` : ''} · ${esc(doc.period)} · Generated ${esc(doc.generatedAt.toUTCString())}</div></header>
${doc.sections.map(section).join('\n')}
<footer>Generated by AmpliVerify from your project data.</footer>
</main></body></html>`;
}

/** Simple branded PDF with the same content as the HTML report. */
export function renderPdf(doc: ReportDoc): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const pdf = new PDFDocument({ size: 'A4', margin: 48, info: { Title: doc.title, Author: 'AmpliVerify' } });
    const chunks: Buffer[] = [];
    pdf.on('data', (c: Buffer) => chunks.push(c));
    pdf.on('end', () => resolve(Buffer.concat(chunks)));
    pdf.on('error', reject);

    pdf.fillColor('#0B3D2E').fontSize(9).text('AMPLIVERIFY · AUDIT • OPTIMIZE • VERIFY', { characterSpacing: 1 });
    pdf.moveDown(0.4).fillColor('#0f172a').fontSize(22).text(doc.title);
    pdf.fillColor('#475569').fontSize(10).text(`${doc.projectName}${doc.domain ? ` · ${doc.domain}` : ''} · ${doc.period} · Generated ${doc.generatedAt.toUTCString()}`);
    pdf.moveDown(0.5).strokeColor('#16B364').lineWidth(2).moveTo(48, pdf.y).lineTo(547, pdf.y).stroke();

    for (const s of doc.sections) {
      pdf.moveDown(1).fillColor('#0B3D2E').fontSize(14).text(s.title);
      if (s.summary) pdf.moveDown(0.3).fillColor('#334155').fontSize(10).text(s.summary);
      if (s.metrics?.length) {
        pdf.moveDown(0.3).fillColor('#0f172a').fontSize(10).text(s.metrics.map((m) => `${m.label}: ${m.value}`).join('   ·   '));
      }
      for (const b of s.bullets ?? []) pdf.moveDown(0.2).fillColor('#0f172a').fontSize(10).text(`• ${b}`, { indent: 8 });
      if (s.table?.rows.length) {
        pdf.moveDown(0.4).fontSize(9).fillColor('#64748b').text(s.table.columns.join('  |  '));
        for (const r of s.table.rows.slice(0, 60)) pdf.fillColor('#0f172a').text(r.join('  |  '));
      }
      if (s.empty && !s.table?.rows.length && !s.bullets?.length && !s.metrics?.length) pdf.moveDown(0.3).fillColor('#64748b').fontSize(10).text(s.empty);
    }
    pdf.end();
  });
}

export function renderCsv(sections: SectionPayload[]) {
  // Quote every cell and neutralize spreadsheet formulas (CSV injection).
  const cell = (v: string) => `"${(/^[=+\-@\t\r]/.test(v) ? `'${v}` : v).replace(/"/g, '""')}"`;
  const lines: string[] = [];
  for (const s of sections) {
    if (!s.table?.rows.length) continue;
    lines.push(cell(s.title));
    lines.push(s.table.columns.map(cell).join(','));
    for (const r of s.table.rows) lines.push(r.map(cell).join(','));
    lines.push('');
  }
  return lines.join('\n');
}
