import { Bell } from 'lucide-react';
import { ButtonLink, EmptyState, PageHeader, Panel, TabNav } from '@/components/ui';
import { ActionButton } from '@/components/ui/actions';
import { apiGet } from '@/lib/api';
import type { NotificationItem } from '@/lib/app-types';
import { formatDateTime } from '@/lib/format';

export const metadata = { title: 'Notifications' };

/** Header-bell destination: in-app notifications generated by real product events. */
export default async function NotificationCenterPage({ searchParams }: { searchParams: Promise<{ filter?: string }> }) {
  const unreadOnly = (await searchParams).filter === 'unread';
  const res = await apiGet<NotificationItem[]>(`/user/notifications?limit=200${unreadOnly ? '&unread=true' : ''}`, { auth: true });
  const items = res.ok ? res.data : [];
  const unread = items.filter((n) => !n.readAt).length;
  return (
    <>
      <PageHeader
        title="Notifications"
        description="Recent account, audit, report, billing, and system notices."
        actions={
          <>
            {unread > 0 && (
              <ActionButton variant="secondary" path="/user/notifications/read-all" revalidate={['/app']}>
                Mark all as read
              </ActionButton>
            )}
            <ButtonLink href="/app/settings/notifications" variant="secondary">
              Notification settings
            </ButtonLink>
          </>
        }
      />
      <TabNav
        active={unreadOnly ? 'unread' : 'all'}
        tabs={[
          { key: 'all', label: 'All', href: '/app/notifications' },
          { key: 'unread', label: 'Unread', href: '/app/notifications?filter=unread' },
        ]}
      />
      <Panel title="Notification Center" bodyless>
        {items.length ? (
          <ul style={{ listStyle: 'none', margin: 0, padding: 0 }}>
            {items.map((n) => (
              <li key={n.id} style={{ display: 'flex', gap: 12, alignItems: 'flex-start', padding: '14px 18px', borderBottom: '1px solid var(--line)', background: n.readAt ? undefined : 'var(--blue-50, #eff6ff)' }}>
                <Bell size={18} style={{ marginTop: 3, color: n.readAt ? 'var(--muted)' : 'var(--blue)' }} />
                <div style={{ flex: 1 }}>
                  <b>{n.title}</b>
                  <p style={{ margin: '4px 0', color: 'var(--muted)', fontSize: 14 }}>{n.body}</p>
                  <small style={{ color: 'var(--muted)' }}>{formatDateTime(n.createdAt)}</small>
                </div>
                {!n.readAt && (
                  <ActionButton size="sm" variant="ghost" path={`/user/notifications/${n.id}/read`} revalidate={['/app']}>
                    Mark read
                  </ActionButton>
                )}
              </li>
            ))}
          </ul>
        ) : (
          <EmptyState icon={<Bell size={26} />} title={unreadOnly ? 'You’re all caught up' : 'No notifications yet'} description="Account, audit, report, billing, and system notices will appear here as they occur." />
        )}
      </Panel>
    </>
  );
}
