import { Bell } from 'lucide-react';
import { ButtonLink, EmptyState, PageHeader, Panel } from '@/components/ui';

export const metadata = { title: 'Notifications' };

/** Header-bell destination: in-app notifications generated by real product events. */
export default function NotificationCenterPage() {
  return (
    <>
      <PageHeader
        title="Notifications"
        description="Recent account, audit, report, billing, and system notices."
        actions={
          <ButtonLink href="/app/settings/notifications" variant="secondary">
            Notification settings
          </ButtonLink>
        }
      />
      <Panel title="Notification Center" description="The header bell opens recent in-app notices." bodyless>
        <EmptyState icon={<Bell size={26} />} title="No notifications yet" description="Account, audit, report, billing, and system notices will appear here as they occur." />
      </Panel>
    </>
  );
}
